# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'prototype' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for prototype

  # Google Firestore
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  # Google Analytics
  pod 'Firebase/Analytics'

  # Google Authentification
  pod 'Firebase/Auth'

  # Google Maps
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  # Google Cloud Storage
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'SDWebImage'

  # Google Cloud Messaging
  pod 'Firebase/Messaging'

end
